./test/should-error/cases_error.pf:1.1-4.10: while parsing
	proof_stmt ::= "theorem" identifier ":" formula "proof" proof "end"
./test/should-error/cases_error.pf:5.5-5.9: expected a closing "}" around proof, not
	case
